BINDER_ROOT_PATH := binder

BINDER_FLAGS := $(CFLAGS)
BINDER_FLAGS += -D__ANDROID__ -Wno-unused-parameter -std=c++11


include $(BINDER_ROOT_PATH)/libutils/Makefile
include $(BINDER_ROOT_PATH)/libbinder/Makefile


